# Generated by Django 3.0.3 on 2020-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='values',
            new_name='length',
        ),
        migrations.AddField(
            model_name='column',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
